### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by x4x5c5** [Adyzng/jd-autobuy#1]
-c COUNT是什么意思,结帐?要输入int?
![image](https://cloud.githubusercontent.com/assets/18498743/18228695/f5fc8150-728b-11e6-85cf-774f505f51e1.png)

**Comment by Adyzng** [comment]
购买数量，默认值为1

**Comment by wuqianming** [comment]
为什么我运行不了，提示如下
C:\Python27\python.exe C:/Users/wuqianming/Desktop/jd-autobuy-master/scraper-jd.py
  File "C:/Users/wuqianming/Desktop/jd-autobuy-master/scraper-jd.py", line 572
    return
SyntaxError: 'return' outside function

**Comment by Adyzng** [comment]
try again

**Comment by wuqianming** [comment]
试了几次都没用，还是这个错误

**Comment by wuqianming** [comment]
python 2.7.11

**Comment by Adyzng** [comment]
代码已更新，重新下载
还有是因为输入参数你没给用户名

**Comment by wuqianming** [comment]
我加了参数，还是有问题

**Comment by wuqianming** [comment]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Sat Sep 17 02:12:05 2016 > 登陆
Exception: list index out of range
list index out of range
Traceback (most recent call last):
  File "C:/Users/wuqianming/Desktop/jd-autobuy-master/scraper-jd.py", line 577, in <module>
    while not jd.buy(options) and options.flush:
  File "C:/Users/wuqianming/Desktop/jd-autobuy-master/scraper-jd.py", line 359, in buy
    good_data = self.good_detail(options.good)
  File "C:/Users/wuqianming/Desktop/jd-autobuy-master/scraper-jd.py", line 318, in good_detail
    good_data['stock'] = self.good_stock(stock_id)
  File "C:/Users/wuqianming/Desktop/jd-autobuy-master/scraper-jd.py", line 256, in good_stock
    'skuNum' : stock_id + ',' + str(good_count),
NameError: global name 'good_count' is not defined

**Comment by wuqianming** [comment]
256行有误，应该是stock_id不是good_count

**Comment by wuqianming** [comment]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Sat Sep 17 11:14:55 2016 > 登陆
Exception: list index out of range
list index out of range
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Sat Sep 17 11:14:59 2016 > 商品详情
编号：3180350
库存：有货
价格：288.00
名称：【活动商品】小米（MI）小米手环2 心率监测 来电提醒
链接：http://cart.jd.com/gate.action?pid=3180350&pcount=1&ptype=1
商品已成功加入购物车！
购买数量：3180350 > 2
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Sat Sep 17 11:14:59 2016 > 购物车明细
购买    数量    价格        总价        商品
 Y      2       288.00      576.00      【活动商品】小米（MI）小米手环2 心率监测 来电提醒
总数: 2
总额: ￥576.00
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Sat Sep 17 11:14:59 2016 > 订单详情

**Comment by Adyzng** [comment]
少一默认参数`good_count`，代码已修改
谢谢

**Comment by wuqianming** [comment]
每次运行都要登录，建议可以保存cookie，登录一次后免登录

**Comment by bravolover520** [comment]
今天试了下不能登录了。AttributeError: 'JDWrapper' object has no attribute 'browser'，持续关注中。

**Comment by Adyzng** [comment]
应该是PhantomJS没有安装，或者有问题，请看ReadMe
代码已添加了这种错误处理，请更新代码

**Comment by bravolover520** [comment]
PhantomJS.exe download url:
https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by Adyzng** [comment]
为什么不去官网下
http://phantomjs.org/
