### ISSUE TITLE
二维码登陆失败

### ISSUE THREAD

**Issue by dlinkqu** [Adyzng/jd-autobuy#10]
二维码获取不完整，导致JD客户端无法扫码登陆。

**Comment by Adyzng** [comment]
我测试正常啊

+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Wed Mar 29 10:34:31 2017 > 请打开京东手机客户端，准备扫码登陆:
201 : 二维码未扫描 ，请扫描二维码
201 : 二维码未扫描 ，请扫描二维码
201 : 二维码未扫描 ，请扫描二维码
201 : 二维码未扫描 ，请扫描二维码
201 : 二维码未扫描 ，请扫描二维码
201 : 二维码未扫描 ，请扫描二维码
202 : 请手机客户端确认登录
202 : 请手机客户端确认登录
200 : AAEAIE0fnjE7Cc-_s7cgwj6dIoTlUKqgZMu7B_z_QWF_bd0-
登陆成功
+++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by dlinkqu** [comment]
![Uploading qr.png…
![Uploading qr.png…]()
]()

为什么我这边下载下来的二维码好像变形的呢？手机扫描不到。。。

**Comment by dlinkqu** [comment]
![qr](https://cloud.githubusercontent.com/assets/12165758/24436130/55030778-146c-11e7-9e56-148ea0a5e0f0.png)
为什么我这边下载下来的二维码好像变形的呢？手机扫描不到。。

**Comment by dlinkqu** [comment]
哎，原来是win10的图片浏览软件的问题，用其他程序打开可以登录了，感谢大神。
