### ISSUE TITLE
商品数量设置无效

### ISSUE THREAD

**Issue by leiyugithub** [Adyzng/jd-autobuy#27]
我修改了count的default数量大于1 但是下单结果都是1一件商品 测试商品编号为：1752931705 请问大家有这个问题吗

**Comment by leiyugithub** [comment]
@Adyzng 大神给看看呢

**Comment by leiyugithub** [comment]
加入购物车的数量 和设置的数量是一直的 但是下单的时候 数量又变成1了

**Comment by Adyzng** [comment]
[fix open QR image by OS, fix buy count not work for third party vender](https://github.com/Adyzng/jd-autobuy/commit/31b71e67b2e8981e645885abed4b25b83bde6dad)

已经修改过来了
