### ISSUE TITLE
Login exception

### ISSUE THREAD

**Issue by jacksPeak** [Adyzng/jd-autobuy#28]
I run the script to get the following results
![81510804775_ pic_hd](https://user-images.githubusercontent.com/13911593/32873184-b3dbb2c6-cac5-11e7-8a8d-741c3021131d.jpg)

**Comment by happyHou** [comment]
如果在mac下换成open，start命令找不到
        os.system('open ' + image_file)

**Comment by jacksPeak** [comment]
ok, thank you very much

**Comment by Adyzng** [comment]
[fix open QR image by OS, fix buy count not work for third party vender](https://github.com/Adyzng/jd-autobuy/commit/31b71e67b2e8981e645885abed4b25b83bde6dad)

已经修改过来了

**Comment by jacksPeak** [comment]
好的👌
