### ISSUE TITLE
获取验证码的问题

### ISSUE THREAD

**Issue by gechanghang** [Adyzng/jd-autobuy#3]
获得的验证码永远都是KWHT之类的固定几个，看了GET的URL感觉没什么问题啊，不知道是哪里出了问题

**Comment by Adyzng** [comment]
验证码这块确实有问题，当初就是没搞明白到底怎么获取，才选择的PhantomJS。
之前用PhantomJS可以登录，最近好像JD升级又不行了。
有兴趣你也可以继续研究吧

**Comment by Adyzng** [comment]
试试新版二维码登陆
