### ISSUE TITLE
扫码登录报错 Exp: 'dict' object has no attribute 'url'

### ISSUE THREAD

**Issue by babutree** [Adyzng/jd-autobuy#34]
作者 您好！
两个问题：
1. 扫码没有边框 JD APP 扫码困难，我的解决办法是点图片编辑-裁剪和旋转 有了边框就能扫码成功

2.扫码后登录失败
![image](https://user-images.githubusercontent.com/21240045/33560395-9421cefa-d94a-11e7-8910-e222d0b7ad4e.png)

谢谢！

**Comment by wuyi365** [comment]
作者很忙，我代替回答下，稍微改动下就好：

if not res['url']:

**Comment by babutree** [comment]
谢谢！已解决！
