### ISSUE TITLE
查询库存的api是http://ss.jd.com/ss/areaStockState/mget?，但是本地抓包查看不是这个地址

### ISSUE THREAD

**Issue by JInghfut** [Adyzng/jd-autobuy#6]
代码里的查询库存接口是ss.jd.com，请问下这个是从哪里获得的呢，本地抓包发现查询库存的地址是http://c0.3.cn/stock?skuId=&venderId=&cat=670,699,701&area=&buyNum=1&extraParam=&ch=1

**Comment by Adyzng** [comment]
Chrome调试窗口看看发了那些网络请求

**Comment by Adyzng** [comment]
京东库存接口确实改了，已经修改代码。
