### ISSUE TITLE
遇到密码错误的问题。

### ISSUE THREAD

**Issue by anChaOs** [Adyzng/jd-autobuy#8]
我看了京东登陆，密码是用JsEncrypt加密的
这个模块是否需要修改加密？

**Comment by Adyzng** [comment]
看来最近又该了登陆方式，难怪最近这个模块一直登陆不了。
能把加密方法公钥之类的弄出来吗？然后需要在这个模块里加上。

**Comment by Adyzng** [comment]
已经搞定二维码登陆，不再需要密码了
