### ISSUE TITLE
ssl error CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by hahahehe775** [Adyzng/jd-autobuy#9]
## Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
刚让代码下载，运行还正常。今天又运行突然发现无法登陆了。 登陆是JD的大难提。求解决。

**Comment by Adyzng** [comment]
登陆方式总是在变，很难搞哇

**Comment by yiqian987** [comment]
我提个思路，通过qq或者微信的第三方接口进行登录，拿到登录的二维码或者api，从而进行扫描二维码登录。如何？

**Comment by Adyzng** [comment]
注意不错，已经搞定京东二维码登陆，拿京东手机客户端扫码登陆。
